### ISSUE TITLE
Tracker: Backport 4.0 code to 3.5

### ISSUE THREAD

**Issue by yaelatletl** [edbeeching/godot_rl_agents#58]
We could probably do both releases at the same time, as people still use Godot 3.5.

- [X] Ported GDScript changes
- [x] Ported Python changes
- [ ] Ported examples changes
- [ ] Follow new structure (submodules, separate examples)

**Comment by yaelatletl** [comment]
I ported the python changes, now I just need to add the export to both baselines and SF

**Comment by edbeeching** [comment]
@yaelatletl I'm closing this as I think we have moved to Godot 4 only now?
